// <auto-generated />
using Baza;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Baza.Migrations
{
    [DbContext(typeof(Wypozyczenia))]
    partial class WypozyczeniacsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Baza.Klienci", b =>
                {
                    b.Property<int>("KlienciId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Imie");

                    b.Property<string>("Nazwisko");

                    b.Property<string>("NumerDowodu");

                    b.Property<string>("Pesel");

                    b.Property<int>("SamochodyId");

                    b.HasKey("KlienciId");

                    b.HasIndex("SamochodyId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Baza.Samochody", b =>
                {
                    b.Property<int>("SamochodyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KonieMechaniczne");

                    b.Property<string>("Marka");

                    b.Property<string>("Model");

                    b.Property<string>("Rok");

                    b.HasKey("SamochodyId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Baza.Klienci", b =>
                {
                    b.HasOne("Baza.Samochody", "Samochody")
                        .WithMany("Kliencis")
                        .HasForeignKey("SamochodyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
